-- A transaction-local helper; no persistent validator or extension is installed.
CREATE FUNCTION pg_temp.structure(ns text)
RETURNS TABLE (object_name text, definition jsonb)
LANGUAGE sql AS $function$
    SELECT c.relname::text, jsonb_build_object(
        'kind', c.relkind, 'owner', pg_get_userbyid(c.relowner),
        'persistence', c.relpersistence, 'rls', c.relrowsecurity,
        'force_rls', c.relforcerowsecurity, 'acl', c.relacl::text,
        'options', c.reloptions, 'replica_identity', c.relreplident,
        'columns', (SELECT jsonb_agg(jsonb_build_array(
            a.attname, format_type(a.atttypid,a.atttypmod), a.attnotnull,
            a.attidentity, a.attgenerated, co.collname, a.attacl::text,
            replace(pg_get_expr(d.adbin,d.adrelid),quote_ident(ns)||'.','@.')
        ) ORDER BY a.attnum)
            FROM pg_attribute a
            LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
            LEFT JOIN pg_collation co ON co.oid=a.attcollation
            WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),
        'constraints', (SELECT jsonb_agg(jsonb_build_array(
            k.conname, replace(pg_get_constraintdef(k.oid,true),quote_ident(ns)||'.','@.'),
            k.convalidated, k.condeferrable, k.condeferred
        ) ORDER BY k.conname) FROM pg_constraint k WHERE k.conrelid=c.oid),
        'indexes', (SELECT jsonb_agg(jsonb_build_array(
            ic.relname, replace(pg_get_indexdef(i.indexrelid),quote_ident(ns)||'.','@.'),
            i.indisvalid, i.indisready, i.indisreplident, ic.reloptions
        ) ORDER BY ic.relname) FROM pg_index i JOIN pg_class ic ON ic.oid=i.indexrelid WHERE i.indrelid=c.oid),
        -- FK enforcement uses internal triggers on both referencing and referenced
        -- tables. Only non-default modes are drift: autogenerated trigger names/OIDs
        -- differ in the expected schema, and a compatible partial schema can have
        -- fewer incoming FK triggers until its missing tables are created.
        'foreign_key_trigger_overrides', (SELECT jsonb_agg(jsonb_build_array(
            k.conname, t.tgenabled
        ) ORDER BY k.conname, t.tgenabled)
            FROM pg_trigger t JOIN pg_constraint k ON k.oid=t.tgconstraint
            WHERE t.tgrelid=c.oid AND t.tgisinternal AND k.contype='f' AND t.tgenabled<>'O'),
        'triggers', (SELECT jsonb_agg(pg_get_triggerdef(t.oid) ORDER BY t.tgname)
            FROM pg_trigger t WHERE t.tgrelid=c.oid AND NOT t.tgisinternal),
        'policies', (SELECT jsonb_agg(p.polname ORDER BY p.polname) FROM pg_policy p WHERE p.polrelid=c.oid),
        'rules', (SELECT jsonb_agg(pg_get_ruledef(r.oid) ORDER BY r.rulename) FROM pg_rewrite r WHERE r.ev_class=c.oid)
    )
    FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname=ns AND c.relkind NOT IN ('i','I');
$function$;
